### ISSUE TITLE
How to prepare the CUB_200_2011/birds/train/attn_embeddings.npy

### ISSUE THREAD

**Issue by haruka0000** [dougsouza/efficient-t2i#3]
Hi. 

Thank you for opening codes of efficiet-t2i.  I've been interested in this since the paper was uploaded to arxiv. I would like to try on my dataset. I predict this file(`CUB_200_2011/birds/train/attn_embeddings.npy`) was made by the AttnGAN's prepare_DAMSM.py, is it correct?

I look forward to hearing from you.

**Comment by dougsouza** [comment]
@haruka0000,

Yes, those embeddings were extracted from the DAMSM module from AttnGAN. If you want to train on your own dataset, first you need to train a DAMSM encoder to encode your text descriptions.

Cheers,

Douglas

**Comment by haruka0000** [comment]
Thank you for your quick reply. I'll try it.

Cheers,

Haruka
